#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListadoAlumnos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LISTADO_ALUMNOS")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ListadoAlumnos.Properties.Settings.Default.LISTADO_ALUMNOSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscar_codigoAlumno")]
		public ISingleResult<buscar_codigoAlumnoResult> buscar_codigoAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
			return ((ISingleResult<buscar_codigoAlumnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscar_DNIAlumno")]
		public ISingleResult<buscar_DNIAlumnoResult> buscar_DNIAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="VarChar(10)")] string dNI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dNI);
			return ((ISingleResult<buscar_DNIAlumnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrar_datos")]
		public ISingleResult<mostrar_datosResult> mostrar_datos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrar_datosResult>)(result.ReturnValue));
		}
	}
	
	public partial class buscar_codigoAlumnoResult
	{
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DNI;
		
		private string _TURNO;
		
		private string _SEXO;
		
		private System.Nullable<bool> _REPETIDOR;
		
		private string _MODULO;
		
		private string _ESPECIALIDAD;
		
		public buscar_codigoAlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL")]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(30)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="NVarChar(10)")]
		public string TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="NVarChar(10)")]
		public string SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPETIDOR", DbType="Bit")]
		public System.Nullable<bool> REPETIDOR
		{
			get
			{
				return this._REPETIDOR;
			}
			set
			{
				if ((this._REPETIDOR != value))
				{
					this._REPETIDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULO", DbType="NVarChar(10)")]
		public string MODULO
		{
			get
			{
				return this._MODULO;
			}
			set
			{
				if ((this._MODULO != value))
				{
					this._MODULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIALIDAD", DbType="NVarChar(25)")]
		public string ESPECIALIDAD
		{
			get
			{
				return this._ESPECIALIDAD;
			}
			set
			{
				if ((this._ESPECIALIDAD != value))
				{
					this._ESPECIALIDAD = value;
				}
			}
		}
	}
	
	public partial class buscar_DNIAlumnoResult
	{
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DNI;
		
		private string _TURNO;
		
		private string _SEXO;
		
		private System.Nullable<bool> _REPETIDOR;
		
		private string _MODULO;
		
		private string _ESPECIALIDAD;
		
		public buscar_DNIAlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL")]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(30)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="NVarChar(10)")]
		public string TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="NVarChar(10)")]
		public string SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPETIDOR", DbType="Bit")]
		public System.Nullable<bool> REPETIDOR
		{
			get
			{
				return this._REPETIDOR;
			}
			set
			{
				if ((this._REPETIDOR != value))
				{
					this._REPETIDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULO", DbType="NVarChar(10)")]
		public string MODULO
		{
			get
			{
				return this._MODULO;
			}
			set
			{
				if ((this._MODULO != value))
				{
					this._MODULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIALIDAD", DbType="NVarChar(25)")]
		public string ESPECIALIDAD
		{
			get
			{
				return this._ESPECIALIDAD;
			}
			set
			{
				if ((this._ESPECIALIDAD != value))
				{
					this._ESPECIALIDAD = value;
				}
			}
		}
	}
	
	public partial class mostrar_datosResult
	{
		
		private int _CODIGO;
		
		private string _NOMBRE;
		
		private string _DNI;
		
		private string _TURNO;
		
		private string _SEXO;
		
		private System.Nullable<bool> _REPETIDOR;
		
		private string _MODULO;
		
		private string _ESPECIALIDAD;
		
		public mostrar_datosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int NOT NULL")]
		public int CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(30)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURNO", DbType="NVarChar(10)")]
		public string TURNO
		{
			get
			{
				return this._TURNO;
			}
			set
			{
				if ((this._TURNO != value))
				{
					this._TURNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="NVarChar(10)")]
		public string SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPETIDOR", DbType="Bit")]
		public System.Nullable<bool> REPETIDOR
		{
			get
			{
				return this._REPETIDOR;
			}
			set
			{
				if ((this._REPETIDOR != value))
				{
					this._REPETIDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULO", DbType="NVarChar(10)")]
		public string MODULO
		{
			get
			{
				return this._MODULO;
			}
			set
			{
				if ((this._MODULO != value))
				{
					this._MODULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIALIDAD", DbType="NVarChar(25)")]
		public string ESPECIALIDAD
		{
			get
			{
				return this._ESPECIALIDAD;
			}
			set
			{
				if ((this._ESPECIALIDAD != value))
				{
					this._ESPECIALIDAD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
