#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepasoJueves
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="REPASO_JUEVES")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::RepasoJueves.Properties.Settings.Default.REPASO_JUEVESConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[EliminarCliente JUEVES]")]
		public int EliminarCliente_JUEVES([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellidos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apellidos);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insertarcliente")]
		public int Insertarcliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string idcliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombres)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idcliente, apellidos, nombres);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarcliente")]
		public int modificarcliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string idcliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellidos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idcliente, nombres, apellidos);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarClientes")]
		public ISingleResult<MostrarClientesResult> MostrarClientes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string idcliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idcliente);
			return ((ISingleResult<MostrarClientesResult>)(result.ReturnValue));
		}
	}
	
	public partial class MostrarClientesResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		private string _IDCLIENTE1;
		
		private string _IDCUENTA;
		
		private System.Nullable<double> _SALDO;
		
		private string _DIVISA;
		
		private string _IDCUENTA1;
		
		private string _IDMOVIMIENTO;
		
		private string _TIPO;
		
		private System.Nullable<double> _MONTO;
		
		private System.Nullable<System.DateTime> _FECHA;
		
		public MostrarClientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE1", DbType="VarChar(5)")]
		public string IDCLIENTE1
		{
			get
			{
				return this._IDCLIENTE1;
			}
			set
			{
				if ((this._IDCLIENTE1 != value))
				{
					this._IDCLIENTE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCUENTA", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCUENTA
		{
			get
			{
				return this._IDCUENTA;
			}
			set
			{
				if ((this._IDCUENTA != value))
				{
					this._IDCUENTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO", DbType="Float")]
		public System.Nullable<double> SALDO
		{
			get
			{
				return this._SALDO;
			}
			set
			{
				if ((this._SALDO != value))
				{
					this._SALDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISA", DbType="VarChar(20)")]
		public string DIVISA
		{
			get
			{
				return this._DIVISA;
			}
			set
			{
				if ((this._DIVISA != value))
				{
					this._DIVISA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCUENTA1", DbType="VarChar(5)")]
		public string IDCUENTA1
		{
			get
			{
				return this._IDCUENTA1;
			}
			set
			{
				if ((this._IDCUENTA1 != value))
				{
					this._IDCUENTA1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMOVIMIENTO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDMOVIMIENTO
		{
			get
			{
				return this._IDMOVIMIENTO;
			}
			set
			{
				if ((this._IDMOVIMIENTO != value))
				{
					this._IDMOVIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(20)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this._TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Float")]
		public System.Nullable<double> MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this._MONTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this._FECHA = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
