CREATE PROCEDURE MostrarClientes
@idcliente varchar(5)
AS
SELECT *
FROM CLIENTE INNER JOIN CUENTA 
ON CLIENTE.IDCLIENTE=CUENTA.IDCLIENTE 
INNER JOIN MOVIMIENTO
ON CUENTA.IDCUENTA=MOVIMIENTO.IDCUENTA
WHERE cliente.idcliente=@idcliente;


EXEC MostrarClientes 'B13';